import {
  Document, Packer, Paragraph, Table, TableRow, TableCell,
  TextRun, HeadingLevel, AlignmentType, WidthType, BorderStyle,
  ShadingType, convertInchesToTwip,
} from "docx";

const BLUE = "1E3A8A";
const LIGHT_BLUE = "DBEAFE";
const GRAY_BG = "F8FAFC";

function safeStr(v: unknown): string {
  if (v == null) return "—";
  if (typeof v === "object") return JSON.stringify(v);
  return String(v);
}

function heading(text: string, level: typeof HeadingLevel[keyof typeof HeadingLevel] = HeadingLevel.HEADING_1) {
  return new Paragraph({
    text,
    heading: level,
    spacing: { before: 240, after: 120 },
    border: level === HeadingLevel.HEADING_1 ? { bottom: { style: BorderStyle.SINGLE, color: BLUE, size: 8 } } : undefined,
  });
}

function para(text: string, bold = false, color?: string) {
  return new Paragraph({
    children: [new TextRun({ text, bold, color, size: 22 })],
    spacing: { after: 80 },
  });
}

function bullet(text: string) {
  return new Paragraph({
    children: [new TextRun({ text, size: 22 })],
    bullet: { level: 0 },
    spacing: { after: 60 },
  });
}

function fieldRow(label: string, value: string) {
  return new Paragraph({
    children: [
      new TextRun({ text: `${label}: `, bold: true, size: 22, color: "374151" }),
      new TextRun({ text: value, size: 22 }),
    ],
    spacing: { after: 80 },
  });
}

function dataTable(headers: string[], rows: string[][]): Table {
  const headerCells = headers.map((h) =>
    new TableCell({
      children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 })] })],
      shading: { fill: BLUE, type: ShadingType.CLEAR, color: "auto" },
      margins: { top: 60, bottom: 60, left: 80, right: 80 },
    })
  );

  const dataRows = rows.map((row, ri) =>
    new TableRow({
      children: row.map((cell) =>
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: cell, size: 20 })] })],
          shading: { fill: ri % 2 === 0 ? "FFFFFF" : GRAY_BG, type: ShadingType.CLEAR, color: "auto" },
          margins: { top: 60, bottom: 60, left: 80, right: 80 },
        })
      ),
    })
  );

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [new TableRow({ children: headerCells, tableHeader: true }), ...dataRows],
    margins: { top: 60, bottom: 60, left: 80, right: 80 },
  });
}

function spacer() {
  return new Paragraph({ text: "", spacing: { after: 160 } });
}

// ── builders ──────────────────────────────────────────────────────────────────

const AI_DISCLAIMER_PARAGRAPH = new Paragraph({
  children: [
    new TextRun({
      text: "AI-Generated Draft — Reviewed and approved by: __________________ | This document was generated by an AI assistant. The Project Manager is responsible for validating all content before use.",
      italics: true,
      size: 18,
      color: "6B7280",
    }),
  ],
  shading: { type: ShadingType.CLEAR, fill: "FFFBEB" },
  border: {
    top:    { style: BorderStyle.SINGLE, color: "FCD34D", size: 4 },
    bottom: { style: BorderStyle.SINGLE, color: "FCD34D", size: 4 },
    left:   { style: BorderStyle.SINGLE, color: "FCD34D", size: 4 },
    right:  { style: BorderStyle.SINGLE, color: "FCD34D", size: 4 },
  },
  spacing: { before: 0, after: 200 },
});

function buildGenericDoc(title: string, content: any): (Paragraph | Table)[] {
  const children: (Paragraph | Table)[] = [
    AI_DISCLAIMER_PARAGRAPH,
    heading(title),
    spacer(),
  ];

  function addValue(key: string, value: unknown, depth: number) {
    const label = key.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase());
    if (value == null) return;

    if (Array.isArray(value)) {
      if (value.length === 0) return;
      children.push(heading(label, depth === 0 ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3));
      if (typeof value[0] === "object" && value[0] !== null) {
        const keys = Object.keys(value[0] as object).filter((k) => k !== "id");
        children.push(dataTable(
          keys.map((k) => k.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase())),
          (value as Record<string, unknown>[]).map((row) => keys.map((k) => safeStr(row[k])))
        ));
      } else {
        for (const item of value) children.push(bullet(safeStr(item)));
      }
      children.push(spacer());
    } else if (typeof value === "object") {
      children.push(heading(label, depth === 0 ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3));
      for (const [k, v] of Object.entries(value as object)) {
        if (typeof v === "string" || typeof v === "number") {
          children.push(fieldRow(k.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase()), safeStr(v)));
        } else {
          addValue(k, v, depth + 1);
        }
      }
      children.push(spacer());
    } else {
      children.push(fieldRow(label, safeStr(value)));
    }
  }

  for (const [key, value] of Object.entries(content)) {
    addValue(key, value, 0);
  }

  return children;
}

// ── project charter — PMI 8-section renderer ──────────────────────────────────

function buildCharterDoc(content: any): (Paragraph | Table)[] {
  const children: (Paragraph | Table)[] = [
    AI_DISCLAIMER_PARAGRAPH,
    heading("Project Charter"),
    spacer(),
  ];

  // 1 — General Information
  children.push(heading("1. General Information", HeadingLevel.HEADING_2));
  if (content.projectTitle)     children.push(fieldRow("Project Title",  safeStr(content.projectTitle)));
  if (content.projectCode)      children.push(fieldRow("Project Code",   safeStr(content.projectCode)));
  if (content.version)          children.push(fieldRow("Version",        safeStr(content.version)));
  if (content.date)             children.push(fieldRow("Date",           safeStr(content.date)));
  if (content.projectStartDate) children.push(fieldRow("Start Date",     safeStr(content.projectStartDate)));
  if (content.projectEndDate)   children.push(fieldRow("End Date",       safeStr(content.projectEndDate)));
  if (content.preparedBy)       children.push(fieldRow("Prepared By",    safeStr(content.preparedBy)));
  if (content.approvedBy)       children.push(fieldRow("Approved By",    safeStr(content.approvedBy)));
  if (content.pmAuthority)      children.push(fieldRow("PM Authority",   safeStr(content.pmAuthority)));
  children.push(spacer());

  // 2 — Project Purpose & Business Case
  children.push(heading("2. Project Purpose & Business Case", HeadingLevel.HEADING_2));
  if (content.projectDescription) children.push(para(safeStr(content.projectDescription)));
  if (content.businessCase) {
    children.push(heading("Business Case", HeadingLevel.HEADING_3));
    children.push(para(safeStr(content.businessCase)));
  }
  children.push(spacer());

  // 3 — Measurable Objectives (SMART)
  children.push(heading("3. Measurable Objectives (SMART)", HeadingLevel.HEADING_2));
  if (Array.isArray(content.objectives)) {
    for (const obj of content.objectives) children.push(bullet(safeStr(obj)));
  }
  if (Array.isArray(content.successCriteria) && content.successCriteria.length > 0) {
    children.push(heading("Success Criteria", HeadingLevel.HEADING_3));
    const scKeys = ["criterion", "measure", "target"];
    children.push(dataTable(
      ["Criterion", "Measure", "Target"],
      content.successCriteria.map((sc: any) => scKeys.map((k) => safeStr(sc[k])))
    ));
  }
  children.push(spacer());

  // 4 — Project Scope
  children.push(heading("4. Project Scope", HeadingLevel.HEADING_2));
  const scope = content.scope ?? {};
  if (Array.isArray(scope.inScope) && scope.inScope.length > 0) {
    children.push(heading("In Scope", HeadingLevel.HEADING_3));
    for (const item of scope.inScope) children.push(bullet(safeStr(item)));
  }
  if (Array.isArray(scope.outOfScope) && scope.outOfScope.length > 0) {
    children.push(heading("Out Of Scope", HeadingLevel.HEADING_3));
    for (const item of scope.outOfScope) children.push(bullet(safeStr(item)));
  }
  if (Array.isArray(content.deliverables) && content.deliverables.length > 0) {
    children.push(heading("Key Deliverables", HeadingLevel.HEADING_3));
    for (const d of content.deliverables) children.push(bullet(safeStr(d)));
  }
  children.push(spacer());

  // 5 — Milestones & Timeline
  children.push(heading("5. Milestones & Timeline", HeadingLevel.HEADING_2));
  if (Array.isArray(content.milestones) && content.milestones.length > 0) {
    children.push(dataTable(
      ["Milestone", "Target Date", "Description"],
      content.milestones.map((m: any) => [safeStr(m.name), safeStr(m.targetDate), safeStr(m.description)])
    ));
  }
  children.push(spacer());

  // 6 — Resources & Budget
  children.push(heading("6. Resources & Budget", HeadingLevel.HEADING_2));
  const budget = content.budget ?? {};
  if (Object.keys(budget).length > 0) {
    children.push(heading("Budget", HeadingLevel.HEADING_3));
    for (const [k, v] of Object.entries(budget)) {
      if (v != null) {
        children.push(fieldRow(
          k.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase()),
          safeStr(v)
        ));
      }
    }
  }
  if (Array.isArray(content.stakeholders) && content.stakeholders.length > 0) {
    children.push(heading("Key Stakeholders", HeadingLevel.HEADING_3));
    const shKeys = ["name", "role", "organization", "power", "interest", "engagementLevel", "notes"];
    const presentKeys = shKeys.filter((k) => content.stakeholders.some((s: any) => s[k] != null && safeStr(s[k]) !== "—"));
    children.push(dataTable(
      presentKeys.map((k) => k.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase())),
      content.stakeholders.map((s: any) => presentKeys.map((k) => safeStr(s[k])))
    ));
  }
  children.push(spacer());

  // 7 — Risks, Assumptions & Constraints
  children.push(heading("7. Risks, Assumptions & Constraints", HeadingLevel.HEADING_2));
  if (Array.isArray(content.risks) && content.risks.length > 0) {
    children.push(heading("Risks", HeadingLevel.HEADING_3));
    for (const r of content.risks) children.push(bullet(safeStr(r)));
  }
  if (Array.isArray(content.assumptions) && content.assumptions.length > 0) {
    children.push(heading("Assumptions", HeadingLevel.HEADING_3));
    for (const a of content.assumptions) children.push(bullet(safeStr(a)));
  }
  if (Array.isArray(content.constraints) && content.constraints.length > 0) {
    children.push(heading("Constraints", HeadingLevel.HEADING_3));
    for (const c of content.constraints) children.push(bullet(safeStr(c)));
  }
  if (Array.isArray(content.conflicts) && content.conflicts.length > 0) {
    children.push(heading("Conflicts & Open Items", HeadingLevel.HEADING_3));
    for (const c of content.conflicts) children.push(bullet(safeStr(c)));
  }
  children.push(spacer());

  // 8 — Sign-off / Approvals
  children.push(heading("8. Sign-off / Approvals", HeadingLevel.HEADING_2));
  if (content.approvalRequirements) {
    children.push(para(safeStr(content.approvalRequirements)));
    children.push(spacer());
  }
  if (Array.isArray(content.approvalSignatures) && content.approvalSignatures.length > 0) {
    children.push(dataTable(
      ["Role", "Name", "Signature", "Date"],
      content.approvalSignatures.map((sig: any) => [
        safeStr(sig.role),
        safeStr(sig.name),
        "___________________________",
        "___________________________",
      ])
    ));
  }
  children.push(spacer());

  return children;
}

// ── main dispatcher ───────────────────────────────────────────────────────────

export async function buildDocx(artifactType: string, content: any): Promise<Buffer> {
  const title = artifactType.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  const children = artifactType === "project_charter"
    ? buildCharterDoc(content)
    : buildGenericDoc(title, content);

  const doc = new Document({
    styles: {
      default: {
        heading1: { run: { bold: true, color: BLUE, size: 28 }, paragraph: { spacing: { before: 240, after: 120 } } },
        heading2: { run: { bold: true, color: "1E40AF", size: 24 }, paragraph: { spacing: { before: 200, after: 80 } } },
        heading3: { run: { bold: true, color: "374151", size: 22 }, paragraph: { spacing: { before: 160, after: 60 } } },
      },
    },
    sections: [{
      properties: {
        page: {
          margin: {
            top: convertInchesToTwip(1),
            bottom: convertInchesToTwip(1),
            left: convertInchesToTwip(1.2),
            right: convertInchesToTwip(1.2),
          },
        },
      },
      children,
    }],
  });

  return Packer.toBuffer(doc);
}
